# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
# reates a sitemap file to help search engines index content
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
# Adds meta tags to help with SEO
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
#  Creates an RSS feed for your posts
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://sammiehsieh.github.io/'
baseurl: ''
title: "Sammie's Blog"
description: 'Work hard, play hard :)'
permalink: pretty
logo: /assets/logos/rubiks-cube-53.png

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
